### ISSUE TITLE
introduce a styles.md 

### ISSUE THREAD

**Issue by marc-portier** [vliz-be-opsci/vliz-be-opsci.github.io#9]
and link it in at some decent location

We could cover a various number of languages where we want to express an opinion on style
but we at least need some coverage for "csv-headers" we want to adhere to (specially in bon context --> see also creating terms lists for those in vliz-be-opsci/NS#6)

**Comment by marc-portier** [comment]
more on styles 

-- we should have an internal style-guide on naming repositories here (it is a mess now)
  *  action to build gh-pages --> suffix -to-pages (not -to-html)
  * never use uppercase / camelcase
  * ro-crate suffixes to use -crate (or -data) -proifile - seed ?

**Comment by github-jnauta** [comment]
We indeed need to create templates that adhere to a specific "VLIZ"-style, both in a way a project is setup (the 'tree' style, if you wish) _and_ also the look of the documentation, website, etc (the 'style'). If we then publish documentation of, say, DMBON and OpenAIS, they should have basically the only thing that should differ is basically the content. This is also necessary for, say, a Sphinx documentation. 

I will try to make a style template for a Readthedocs implementation using Sphinx and, if people like it, we can use that throughout more of our projects. There are probably some struggles arising due to the difference in programming languages used (can we actually generate a Readthedocs for Javascript, or an API?), but we should try to be as consistent as possible in my opinion.
